baseurl: "/"
languageCode: "en-us"
title: "My Site"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About Me
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    #- name: Subscribe
    #  url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Gianluca Mastrantonio](https://www.polito.it/personale?p=041089) 2023 -- {Year} | [Github](https://github.com/GianlucaMastrantonio) | [Researchgate](https://www.researchgate.net/profile/Gianluca-Mastrantonio)"
#params:
#    assets:
#        disableHLJS: true

#https://xyproto.github.io/splash/docs/all.html
pygmentsCodefences: true
pygmentsUseClasses:  false
pygmentsUseClassic:  false
#pygmentsStyle: monokai
#pygmentsStyle: pygments
pygmentsStyle: monokailight   
#pygmentsStyle: emacs
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    noHl: false
    #style: monokai
    #tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

